package diplomski.rad.Aplikacija;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SVETLO = 7;
  public static final int PRETRAZI = 10;
  public static final int IME = 11;
  public static final int OZAGRADA = 19;
  public static final int ZAREZ = 4;
  public static final int SADNJA = 12;
  public static final int VODA = 8;
  public static final int VODA_KW = 17;
  public static final int BERBA = 13;
  public static final int NAVODNIK = 3;
  public static final int BROJ = 22;
  public static final int DUBINA = 15;
  public static final int EOF = 0;
  public static final int MESTO = 6;
  public static final int ZZAGRADA = 20;
  public static final int PRETRAZI_RASPON = 21;
  public static final int error = 1;
  public static final int MESEC = 5;
  public static final int TEXT = 9;
  public static final int MESTO_KW = 14;
  public static final int JEDNAKO = 18;
  public static final int DODAJ = 2;
  public static final int SVETLO_KW = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DODAJ",
  "NAVODNIK",
  "ZAREZ",
  "MESEC",
  "MESTO",
  "SVETLO",
  "VODA",
  "TEXT",
  "PRETRAZI",
  "IME",
  "SADNJA",
  "BERBA",
  "MESTO_KW",
  "DUBINA",
  "SVETLO_KW",
  "VODA_KW",
  "JEDNAKO",
  "OZAGRADA",
  "ZZAGRADA",
  "PRETRAZI_RASPON",
  "BROJ"
  };
}

